### ISSUE TITLE
CHGNet benchmark perfomed very wrong

### ISSUE THREAD

**Issue by BowenD-UCB** [usnistgov/jarvis_leaderboard#220]
Hi, 
I noticed CHGNet has an unimaginable high energy errors on your benchmark.
> 500 meV/atom error  is probably worse than even a mean value predictor.

By some initial checking I found you have devided energy/atom by number of atoms again:
https://github.com/usnistgov/jarvis_leaderboard/blob/7a36ec001b9155cbcfe2698e73b4aa902d9547cd/jarvis_leaderboard/contributions/chgnet_pretrained/jid_vac_alignn.py#L46

![Screen Shot 2023-07-21 at 3 41 35 PM](https://github.com/usnistgov/jarvis_leaderboard/assets/84425382/aabf08e0-59d7-4cd1-b487-00e899f5297d)

And you have probably used energy/atom as the total energy for benchmark comparison:
https://github.com/usnistgov/jarvis_leaderboard/blob/7a36ec001b9155cbcfe2698e73b4aa902d9547cd/jarvis_leaderboard/contributions/chgnet_pretrained/make_pred.py#L17C29-L17C29

![Screen Shot 2023-07-21 at 3 44 37 PM](https://github.com/usnistgov/jarvis_leaderboard/assets/84425382/02cc3ac3-2204-4542-9b38-d5ab72a66b62)

Please read CHGNet documentation for the units of prediction outputs:
https://github.com/CederGroupHub/chgnet

I hope more careful checks can be made before the benchmark is made online.
And I wish this can solve most of the issue of CHGNet error.

**Comment by BowenD-UCB** [comment]
Here is a screen shot of the wrong benchmark
![jarvis](https://github.com/usnistgov/jarvis_leaderboard/assets/84425382/9db27d4d-c626-48df-8b31-1ad98ce61db4)

**Comment by zhongpc** [comment]
BTW, how could the test is submitted before the publication of CHGNet? (on 01-14-2023)
One needs to be really careful and precise when you claim it is a benchmark.

**Comment by knc6** [comment]
Thanks for pointing out this issue, glad to see active engagement by users. One of the core ideas of the leaderboard is to enhance transparency. The leaderboard is still under active development. 

Note [jid_vac_alignn.py](https://github.com/usnistgov/jarvis_leaderboard/blob/main/jarvis_leaderboard/contributions/chgnet_pretrained/) was not used for CHGNet based contributions. Users should look into corresponding run.sh shell script file. 

CHGNet is a contribution, not a benchmark. Definitions are on the [homepage](https://pages.nist.gov/jarvis_leaderboard/#terminologies). Benchmarks usually imply reference data.

A google colab note book for the CHGNet contribution is [here](https://github.com/knc6/jarvis-tools-notebooks/blob/master/jarvis-tools-notebooks/chgnet_prediction.ipynb).

The main website should be updated soon.
